import Link from "next/link";

/**
 * /privacy — Privacy Policy
 * ----------------------------------------------------------------------
 * Structured placeholder. The headings and sentence stubs cover the
 * standard sections most privacy policies need (collection, use, cookies,
 * third parties, security, rights, children, changes, contact). Replace
 * the body text with your legally-reviewed copy before going live —
 * NOTHING here should be treated as a binding legal claim.
 *
 * Design: matches the homepage cream + Inter/Space-Grotesk type system.
 * No animations, no canvases — readable prose page.
 * ──────────────────────────────────────────────────────────────────── */

const LAST_UPDATED = "May 24, 2026";

const SECTIONS: { heading: string; body: string }[] = [
  {
    heading: "1. Introduction",
    body: "SquareUp (“we”, “us”, or “our”) operates joinsquareup.com and the SquareUp customer research platform. This Privacy Policy describes how we collect, use, and share information when you interact with our website, sign up for a pilot, or use our services. By using SquareUp, you agree to the terms outlined here.",
  },
  {
    heading: "2. Information we collect",
    body: "We collect information you provide directly (such as your name, email address, company, and any details shared when you book a pilot or contact us), information generated by your use of the platform (such as study data, interview recordings, transcripts, and analytics), and information collected automatically (such as device type, browser, IP address, and pages visited).",
  },
  {
    heading: "3. How we use your information",
    body: "We use the information we collect to deliver and improve the SquareUp platform, schedule and conduct customer research interviews, generate insights and reports, communicate with you about pilots and product updates, secure our services and prevent abuse, and comply with legal obligations.",
  },
  {
    heading: "4. Cookies and tracking",
    body: "We use cookies and similar technologies (including Google Analytics) to understand how visitors use our website, improve performance, and measure marketing effectiveness. You can disable cookies through your browser settings, though some site features may not work as intended.",
  },
  {
    heading: "5. Third-party services",
    body: "We rely on a small number of trusted vendors to operate SquareUp — including cloud hosting, analytics, scheduling, and email delivery providers. These vendors only receive the data they need to perform their function and are contractually required to protect it. A full list of subprocessors is available on request.",
  },
  {
    heading: "6. Data security",
    body: "We protect your data using industry-standard practices: end-to-end encryption in transit, encryption at rest, role-based access controls, multi-factor authentication for staff, and regular security reviews. We are working toward SOC 2 Type II certification. While no system is perfectly secure, we treat customer data with the seriousness it deserves.",
  },
  {
    heading: "7. Your rights",
    body: "Depending on your jurisdiction, you may have the right to access, correct, export, or delete the personal information we hold about you, restrict or object to certain processing, and withdraw consent at any time. To exercise these rights, email us at the address in the Contact section.",
  },
  {
    heading: "8. Children’s privacy",
    body: "SquareUp is not directed to children under 16, and we do not knowingly collect personal information from children. If you believe a child has provided us with personal information, please contact us so we can delete it.",
  },
  {
    heading: "9. Changes to this policy",
    body: "We may update this Privacy Policy from time to time. When we do, we will revise the “Last updated” date at the top of this page and, for material changes, notify you by email or through the platform.",
  },
  {
    heading: "10. Contact us",
    body: "Questions about this Privacy Policy or about how we handle your data? Email tech.unclutr@gmail.com and we’ll respond promptly.",
  },
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#FBF4EC] text-[#0b132b]">
      <div className="max-w-[760px] mx-auto px-6 sm:px-8 pt-20 sm:pt-28 pb-24">
        {/* Back to home */}
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-[13px] text-[#FF5A36] font-semibold hover:underline mb-10"
        >
          <span aria-hidden>←</span> Back to home
        </Link>

        {/* Header */}
        <h1 className="font-display font-black text-[#0b132b] leading-[1.1] tracking-[-0.025em] text-[clamp(32px,4.5vw,52px)] mb-3">
          Privacy Policy
        </h1>
        <p className="text-[13px] uppercase tracking-[0.12em] font-bold text-[#FF5A36] mb-8">
          Last updated: {LAST_UPDATED}
        </p>

        {/* Body sections */}
        <div className="flex flex-col gap-9">
          {SECTIONS.map((s) => (
            <section key={s.heading}>
              <h2 className="font-display text-[20px] sm:text-[22px] font-extrabold text-[#0b132b] mb-3 tracking-[-0.005em]">
                {s.heading}
              </h2>
              <p className="text-[15px] leading-[1.7] text-[rgba(11,19,43,0.78)]">
                {s.body}
              </p>
            </section>
          ))}
        </div>

        {/* Footer note */}
        <p className="mt-14 text-[12px] text-[#757575] leading-[1.6] italic">
          This document is a structured starting point and is not legal advice.
          Please have your final privacy policy reviewed by qualified counsel
          before relying on it for compliance purposes.
        </p>
      </div>
    </main>
  );
}
