"""add_campaign_and_interview_tables

Revision ID: 11c3c7a6156b
Revises: 2c7c915648d7
Create Date: 2026-01-28 01:32:11.772359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11c3c7a6156b'
down_revision: Union[str, Sequence[str], None] = '2c7c915648d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
