"""add_shopify_raw_payloads

Revision ID: 16e3a6ec1736
Revises: 8d3fcdb663a3
Create Date: 2026-01-11 15:52:59.572545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16e3a6ec1736'
down_revision: Union[str, Sequence[str], None] = '8d3fcdb663a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopify_inventory_item', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('shopify_inventory_level', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('shopify_order', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopify_order', 'raw_payload')
    op.drop_column('shopify_inventory_level', 'raw_payload')
    op.drop_column('shopify_inventory_item', 'raw_payload')
    # ### end Alembic commands ###
