"""restore_bolna_schema

Revision ID: 26e1892bc588
Revises: db16f65b2e80
Create Date: 2026-02-10 03:29:57.902559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '26e1892bc588'
down_revision: Union[str, Sequence[str], None] = 'db16f65b2e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('bolna_execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_call_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_conversation_time', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_total_cost', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_transcript', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_extracted_data', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_telephony_data', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_raw_data', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_created_at', sa.DateTime(), nullable=True))
    op.add_column('campaigns', sa.Column('bolna_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_campaigns_bolna_execution_id'), 'campaigns', ['bolna_execution_id'], unique=True)
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_campaigns_bolna_execution_id'), table_name='campaigns')
    op.drop_column('campaigns', 'bolna_updated_at')
    op.drop_column('campaigns', 'bolna_created_at')
    op.drop_column('campaigns', 'bolna_raw_data')
    op.drop_column('campaigns', 'bolna_telephony_data')
    op.drop_column('campaigns', 'bolna_extracted_data')
    op.drop_column('campaigns', 'bolna_transcript')
    op.drop_column('campaigns', 'bolna_error_message')
    op.drop_column('campaigns', 'bolna_total_cost')
    op.drop_column('campaigns', 'bolna_conversation_time')
    op.drop_column('campaigns', 'bolna_call_status')
    op.drop_column('campaigns', 'bolna_agent_id')
    op.drop_column('campaigns', 'bolna_execution_id')
    # ### end Alembic commands ###
