"""rename_campaign_to_campaigns_and_add_bolna_fields

Revision ID: 32948d82da7f
Revises: b1dad6adf657
Create Date: 2026-01-28 12:00:03.705369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32948d82da7f'
down_revision: Union[str, Sequence[str], None] = 'b1dad6adf657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_company_id'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_interview_session_id'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_user_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.create_table('campaign',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('decision_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quality_gap', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interview_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_pkey'))
    )
    op.create_index(op.f('ix_campaign_user_id'), 'campaign', ['user_id'], unique=False)
    op.create_index(op.f('ix_campaign_interview_session_id'), 'campaign', ['interview_session_id'], unique=False)
    op.create_index(op.f('ix_campaign_company_id'), 'campaign', ['company_id'], unique=False)
    # ### end Alembic commands ###
