"""add_bolna_observability_fields

Revision ID: 339be546ad27
Revises: ee58e4042691
Create Date: 2026-02-02 02:53:22.869002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '339be546ad27'
down_revision: Union[str, Sequence[str], None] = 'ee58e4042691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bolna_execution_maps', sa.Column('total_cost', sa.Float(), nullable=False))
    op.add_column('bolna_execution_maps', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('bolna_execution_maps', sa.Column('call_duration', sa.Integer(), nullable=False))
    op.add_column('bolna_execution_maps', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('bolna_execution_maps', sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bolna_execution_maps', sa.Column('telephony_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bolna_execution_maps', sa.Column('termination_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('bolna_execution_maps', 'duration_seconds')
    op.add_column('campaigns', sa.Column('custom_analytics_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_campaigns_source_file_hash'), table_name='campaigns')
    op.create_index(op.f('ix_campaigns_source_file_hash'), 'campaigns', ['source_file_hash'], unique=False)
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    op.add_column('queue_items', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_queue_items_scheduled_for'), 'queue_items', ['scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_items_scheduled_for'), table_name='queue_items')
    op.drop_column('queue_items', 'scheduled_for')
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_campaigns_source_file_hash'), table_name='campaigns')
    op.create_index(op.f('idx_campaigns_source_file_hash'), 'campaigns', ['source_file_hash'], unique=False)
    op.drop_column('campaigns', 'custom_analytics_config')
    op.add_column('bolna_execution_maps', sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bolna_execution_maps', 'termination_reason')
    op.drop_column('bolna_execution_maps', 'telephony_provider')
    op.drop_column('bolna_execution_maps', 'extracted_data')
    op.drop_column('bolna_execution_maps', 'transcript')
    op.drop_column('bolna_execution_maps', 'call_duration')
    op.drop_column('bolna_execution_maps', 'currency')
    op.drop_column('bolna_execution_maps', 'total_cost')
    # ### end Alembic commands ###
