"""add_campaign_context_and_execution_fields

Revision ID: 37c0ca39fa4e
Revises: a5c26918531c
Create Date: 2026-01-30 04:23:27.055571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37c0ca39fa4e'
down_revision: Union[str, Sequence[str], None] = 'a5c26918531c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('brand_context', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('customer_context', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('team_member_context', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('preliminary_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('incentive', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('total_call_target', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('call_duration_limit', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('cohort_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('execution_windows', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'execution_windows')
    op.drop_column('campaigns', 'cohort_config')
    op.drop_column('campaigns', 'call_duration_limit')
    op.drop_column('campaigns', 'total_call_target')
    op.drop_column('campaigns', 'incentive')
    op.drop_column('campaigns', 'preliminary_questions')
    op.drop_column('campaigns', 'team_member_context')
    op.drop_column('campaigns', 'customer_context')
    op.drop_column('campaigns', 'brand_context')
    # ### end Alembic commands ###
