"""add_user_queue_tables_and_closure_tracking

Revision ID: 37c628d74c2d
Revises: def7375d1ac0
Create Date: 2026-02-05 04:51:29.400881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37c628d74c2d'
down_revision: Union[str, Sequence[str], None] = 'def7375d1ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archived_campaign_leads', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'decision_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'preliminary_questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'question_bank',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'incentive_bank',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'cohort_questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'cohort_incentives',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'cohort_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'selected_cohorts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'execution_windows',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'cohort_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'goal_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('bolna_execution_maps', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('bolna_execution_maps', 'last_webhook_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('brand_metric', 'insights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('calendar_connection', 'credentials',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('call_logs', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('call_logs', 'lead_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('call_logs', 'transcript_summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('call_logs', 'webhook_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_call_logs_copied_to_user_queue'), table_name='call_logs')
    op.drop_constraint(op.f('call_logs_lead_id_fkey'), 'call_logs', type_='foreignkey')
    op.drop_constraint(op.f('call_logs_campaign_id_fkey'), 'call_logs', type_='foreignkey')
    op.drop_constraint(op.f('fk_call_logs_user_queue_item_id'), 'call_logs', type_='foreignkey')
    op.create_foreign_key(None, 'call_logs', 'queue_items', ['user_queue_item_id'], ['id'])
    op.create_foreign_key(None, 'call_logs', 'campaign_leads', ['lead_id'], ['id'])
    op.create_foreign_key(None, 'call_logs', 'campaigns', ['campaign_id'], ['id'])
    op.drop_column('call_logs', 'bolna_agent_id')
    op.alter_column('call_raw_data', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaign_events', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaign_leads', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'decision_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'preliminary_questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'question_bank',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'incentive_bank',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'cohort_questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'cohort_incentives',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'cohort_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'selected_cohorts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'execution_windows',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'cohort_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'execution_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'custom_analytics_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'usage_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'cost_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'agent_extraction',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'custom_extractions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'telephony_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'transfer_call_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'context_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'batch_run_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'latency_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'retry_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'retry_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('cohorts', 'preliminary_questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('cohorts', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('feedback_learning', 'learning_vector',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('insight_feedback', 'verification_intent',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('insight_generation_log', 'insights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('insight_generation_log', 'validation_failures',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('integration', 'metadata_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('integration_daily_metric', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    op.alter_column('interview_sessions', 'metadata_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    
    # Create user_queue_items table (if not exists)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'user_queue_items' not in existing_tables:
        op.create_table('user_queue_items',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('campaign_id', sa.UUID(), nullable=False),
            sa.Column('lead_id', sa.UUID(), nullable=False),
            sa.Column('original_queue_item_id', sa.UUID(), nullable=False),
            sa.Column('call_history', sa.JSON(), nullable=False),
            sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('intent_strength', sa.Float(), nullable=False),
            sa.Column('confirmation_slot', sa.DateTime(), nullable=True),
            sa.Column('detected_at', sa.DateTime(), nullable=False),
            sa.Column('user_call_count', sa.Integer(), nullable=False),
            sa.Column('last_user_call_at', sa.DateTime(), nullable=True),
            sa.Column('user_call_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('retry_count', sa.Integer(), nullable=False),
            sa.Column('max_retries', sa.Integer(), nullable=False),
            sa.Column('retry_scheduled_for', sa.DateTime(), nullable=True),
            sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('closed_at', sa.DateTime(), nullable=True),
            sa.Column('closure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('locked_by_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('locked_at', sa.DateTime(), nullable=True),
            sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
            sa.Column('priority_score', sa.Integer(), nullable=False),
            sa.Column('user_preferences', sa.JSON(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
            sa.ForeignKeyConstraint(['lead_id'], ['campaign_leads.id'], ),
            sa.ForeignKeyConstraint(['original_queue_item_id'], ['queue_items.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_queue_items_campaign_id'), 'user_queue_items', ['campaign_id'], unique=False)
        op.create_index(op.f('ix_user_queue_items_lead_id'), 'user_queue_items', ['lead_id'], unique=False)
        op.create_index(op.f('ix_user_queue_items_original_queue_item_id'), 'user_queue_items', ['original_queue_item_id'], unique=False)
        op.create_index(op.f('ix_user_queue_items_status'), 'user_queue_items', ['status'], unique=False)
        op.create_index(op.f('ix_user_queue_items_priority_score'), 'user_queue_items', ['priority_score'], unique=False)
    
    # Create user_call_logs table (if not exists)
    if 'user_call_logs' not in existing_tables:
        op.create_table('user_call_logs',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('user_queue_item_id', sa.UUID(), nullable=False),
            sa.Column('lead_id', sa.UUID(), nullable=False),
            sa.Column('campaign_id', sa.UUID(), nullable=False),
            sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('next_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('duration', sa.Integer(), nullable=True),
            sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('retry_scheduled_for', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
            sa.ForeignKeyConstraint(['lead_id'], ['campaign_leads.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.ForeignKeyConstraint(['user_queue_item_id'], ['user_queue_items.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_call_logs_user_queue_item_id'), 'user_call_logs', ['user_queue_item_id'], unique=False)
        op.create_index(op.f('ix_user_call_logs_lead_id'), 'user_call_logs', ['lead_id'], unique=False)
        op.create_index(op.f('ix_user_call_logs_campaign_id'), 'user_call_logs', ['campaign_id'], unique=False)
        op.create_index(op.f('ix_user_call_logs_user_id'), 'user_call_logs', ['user_id'], unique=False)
        op.create_index(op.f('ix_user_call_logs_status'), 'user_call_logs', ['status'], unique=False)
        op.create_index(op.f('ix_user_call_logs_created_at'), 'user_call_logs', ['created_at'], unique=False)
    
    # Add columns to queue_items (check if they don't already exist)
    queue_items_columns = [col['name'] for col in inspector.get_columns('queue_items')]
    
    if 'promoted_to_user_queue' not in queue_items_columns:
        op.add_column('queue_items', sa.Column('promoted_to_user_queue', sa.Boolean(), nullable=False, server_default='false'))
    if 'promoted_at' not in queue_items_columns:
        op.add_column('queue_items', sa.Column('promoted_at', sa.DateTime(), nullable=True))
    if 'closure_reason' not in queue_items_columns:
        op.add_column('queue_items', sa.Column('closure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Remove server_default after adding the column
    if 'promoted_to_user_queue' not in queue_items_columns:
        op.alter_column('queue_items', 'promoted_to_user_queue', server_default=None)
    
    op.alter_column('shopify_address', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_analytics_snapshot', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_analytics_snapshot', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_balance_transaction', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_checkout', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_customer', 'default_address',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('shopify_customer', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_daily_metric', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_discount_code', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_dispute', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_fulfillment', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_inventory_item', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_inventory_level', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_location', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_marketing_event', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_order', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_payout', 'summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_payout', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_price_rule', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_product', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_product_image', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_product_variant', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_raw_ingest', 'headers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('shopify_raw_ingest', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('shopify_raw_ingest', 'diff_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('shopify_refund', 'refund_line_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_refund', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_report', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_report_data', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_transaction', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_queue_items', 'locked_by_user_id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_queue_items', 'locked_by_user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('shopify_transaction', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_report_data', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_report', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_refund', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_refund', 'refund_line_items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_raw_ingest', 'diff_summary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_raw_ingest', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_raw_ingest', 'headers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_product_variant', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_product_image', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_product', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_price_rule', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_payout', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_payout', 'summary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_order', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_marketing_event', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_location', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_inventory_level', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_inventory_item', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_fulfillment', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_dispute', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_discount_code', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_daily_metric', 'meta_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_customer', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_customer', 'default_address',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_checkout', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_balance_transaction', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_analytics_snapshot', 'meta_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_analytics_snapshot', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shopify_address', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    
    # Drop user queue tables (in reverse order of creation)
    op.drop_index(op.f('ix_user_call_logs_created_at'), table_name='user_call_logs')
    op.drop_index(op.f('ix_user_call_logs_status'), table_name='user_call_logs')
    op.drop_index(op.f('ix_user_call_logs_user_id'), table_name='user_call_logs')
    op.drop_index(op.f('ix_user_call_logs_campaign_id'), table_name='user_call_logs')
    op.drop_index(op.f('ix_user_call_logs_lead_id'), table_name='user_call_logs')
    op.drop_index(op.f('ix_user_call_logs_user_queue_item_id'), table_name='user_call_logs')
    op.drop_table('user_call_logs')
    
    op.drop_index(op.f('ix_user_queue_items_priority_score'), table_name='user_queue_items')
    op.drop_index(op.f('ix_user_queue_items_status'), table_name='user_queue_items')
    op.drop_index(op.f('ix_user_queue_items_original_queue_item_id'), table_name='user_queue_items')
    op.drop_index(op.f('ix_user_queue_items_lead_id'), table_name='user_queue_items')
    op.drop_index(op.f('ix_user_queue_items_campaign_id'), table_name='user_queue_items')
    op.drop_table('user_queue_items')
    
    # Drop columns from queue_items
    op.drop_column('queue_items', 'closure_reason')
    op.drop_column('queue_items', 'promoted_at')
    op.drop_column('queue_items', 'promoted_to_user_queue')
    op.alter_column('interview_sessions', 'metadata_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.alter_column('integration_daily_metric', 'meta_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('integration', 'metadata_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('insight_generation_log', 'validation_failures',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('insight_generation_log', 'insights',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('insight_feedback', 'verification_intent',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('feedback_learning', 'learning_vector',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cohorts', 'meta_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cohorts', 'preliminary_questions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'raw_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'retry_history',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'retry_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'latency_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'batch_run_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'context_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'transfer_call_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'telephony_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'custom_extractions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'agent_extraction',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'extracted_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'cost_breakdown',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns_goals_details', 'usage_breakdown',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'meta_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'custom_analytics_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'execution_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'cohort_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'execution_windows',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'selected_cohorts',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'cohort_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'cohort_incentives',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'cohort_questions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'incentive_bank',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'question_bank',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'preliminary_questions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaigns', 'decision_context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaign_leads', 'meta_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('campaign_events', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('call_raw_data', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('call_logs', sa.Column('bolna_agent_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_call_logs_user_queue_item_id'), 'call_logs', 'queue_items', ['user_queue_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('call_logs_campaign_id_fkey'), 'call_logs', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('call_logs_lead_id_fkey'), 'call_logs', 'campaign_leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_call_logs_copied_to_user_queue'), 'call_logs', ['copied_to_user_queue'], unique=False)
    op.alter_column('call_logs', 'webhook_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('call_logs', 'transcript_summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('call_logs', 'lead_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('call_logs', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('calendar_connection', 'credentials',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('brand_metric', 'insights',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('bolna_execution_maps', 'last_webhook_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('bolna_execution_maps', 'extracted_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'goal_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'cohort_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'execution_windows',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'selected_cohorts',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'cohort_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'cohort_incentives',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'cohort_questions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'incentive_bank',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'question_bank',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'preliminary_questions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaigns', 'decision_context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('archived_campaign_leads', 'meta_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
