"""initial_consistent_schema

Revision ID: 38df4628b925
Revises: 
Create Date: 2026-01-03 11:07:39.087618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38df4628b925'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_action'), 'audit_trail', ['action'], unique=False)
    op.create_index(op.f('ix_audit_trail_actor_id'), 'audit_trail', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_trail_brand_id'), 'audit_trail', ['brand_id'], unique=False)
    op.create_index(op.f('ix_audit_trail_company_id'), 'audit_trail', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_trail_workspace_id'), 'audit_trail', ['workspace_id'], unique=False)
    op.create_table('business_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('active_users_daily', sa.Integer(), nullable=False),
    sa.Column('active_users_weekly', sa.Integer(), nullable=False),
    sa.Column('active_users_monthly', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('churned_users', sa.Integer(), nullable=False),
    sa.Column('total_companies', sa.Integer(), nullable=False),
    sa.Column('new_companies', sa.Integer(), nullable=False),
    sa.Column('active_companies', sa.Integer(), nullable=False),
    sa.Column('total_workspaces', sa.Integer(), nullable=False),
    sa.Column('new_workspaces', sa.Integer(), nullable=False),
    sa.Column('active_workspaces', sa.Integer(), nullable=False),
    sa.Column('total_integrations', sa.Integer(), nullable=False),
    sa.Column('new_integrations', sa.Integer(), nullable=False),
    sa.Column('active_integrations', sa.Integer(), nullable=False),
    sa.Column('onboarding_started', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Integer(), nullable=False),
    sa.Column('onboarding_completion_rate', sa.Float(), nullable=False),
    sa.Column('avg_session_duration_seconds', sa.Float(), nullable=True),
    sa.Column('avg_page_views_per_user', sa.Float(), nullable=True),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('arr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_metric_metric_date'), 'business_metric', ['metric_date'], unique=True)
    op.create_table('company',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('founded_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('presence_links', sa.JSON(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hq_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support_hours', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stack_summary', sa.JSON(), nullable=True),
    sa.Column('channels_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_brand_name'), 'company', ['brand_name'], unique=False)
    op.create_index(op.f('ix_company_created_by'), 'company', ['created_by'], unique=False)
    op.create_index(op.f('ix_company_updated_by'), 'company', ['updated_by'], unique=False)
    op.create_table('data_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('Storefront', 'Marketplace', 'QuickCommerce', 'Network', 'SocialCommerce', 'Marketing', 'Logistics', 'Payment', 'Accounting', 'Analytics', 'Communication', 'Retention', name='datasourcecategory'), nullable=False),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_coming_soon', sa.Boolean(), nullable=False),
    sa.Column('is_common', sa.Boolean(), nullable=False),
    sa.Column('is_implemented', sa.Boolean(), nullable=False),
    sa.Column('theme_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_category'), 'data_source', ['category'], unique=False)
    op.create_index(op.f('ix_data_source_name'), 'data_source', ['name'], unique=True)
    op.create_index(op.f('ix_data_source_slug'), 'data_source', ['slug'], unique=True)
    op.create_table('data_source_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_request_name'), 'data_source_request', ['name'], unique=False)
    op.create_index(op.f('ix_data_source_request_user_id'), 'data_source_request', ['user_id'], unique=False)
    op.create_table('module',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_state',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_page', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('basics_data', sa.JSON(), nullable=True),
    sa.Column('channels_data', sa.JSON(), nullable=True),
    sa.Column('stack_data', sa.JSON(), nullable=True),
    sa.Column('finish_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_saved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_state_created_by'), 'onboarding_state', ['created_by'], unique=False)
    op.create_index(op.f('ix_onboarding_state_updated_by'), 'onboarding_state', ['updated_by'], unique=False)
    op.create_index(op.f('ix_onboarding_state_user_id'), 'onboarding_state', ['user_id'], unique=True)
    op.create_table('permission',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('api_requests_total', sa.Integer(), nullable=False),
    sa.Column('api_requests_success', sa.Integer(), nullable=False),
    sa.Column('api_requests_error', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('db_connections_active', sa.Integer(), nullable=False),
    sa.Column('db_query_avg_time_ms', sa.Float(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('memory_usage_percent', sa.Float(), nullable=True),
    sa.Column('overall_health_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metric_timestamp'), 'system_metric', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('current_company_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('brand',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name')
    )
    op.create_index(op.f('ix_brand_company_id'), 'brand', ['company_id'], unique=False)
    op.create_index(op.f('ix_brand_created_by'), 'brand', ['created_by'], unique=False)
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=False)
    op.create_index(op.f('ix_brand_updated_by'), 'brand', ['updated_by'], unique=False)
    op.create_table('company_entitlement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'module_id')
    )
    op.create_index(op.f('ix_company_entitlement_company_id'), 'company_entitlement', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_entitlement_module_id'), 'company_entitlement', ['module_id'], unique=False)
    op.create_table('company_membership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='systemrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id')
    )
    op.create_index(op.f('ix_company_membership_company_id'), 'company_membership', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_membership_user_id'), 'company_membership', ['user_id'], unique=False)
    op.create_table('onboarding_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(), nullable=True),
    sa.Column('basics_completed_at', sa.DateTime(), nullable=True),
    sa.Column('channels_completed_at', sa.DateTime(), nullable=True),
    sa.Column('stack_completed_at', sa.DateTime(), nullable=True),
    sa.Column('finish_completed_at', sa.DateTime(), nullable=True),
    sa.Column('basics_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('channels_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('stack_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('finish_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('drawer_opens', sa.Integer(), nullable=False),
    sa.Column('search_uses', sa.Integer(), nullable=False),
    sa.Column('datasources_selected', sa.Integer(), nullable=False),
    sa.Column('integration_requests', sa.Integer(), nullable=False),
    sa.Column('last_step_visited', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drop_off_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_metric_user_id'), 'onboarding_metric', ['user_id'], unique=True)
    op.create_table('user_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('total_session_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('interactions', sa.Integer(), nullable=False),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_metric_metric_date'), 'user_metric', ['metric_date'], unique=False)
    op.create_index(op.f('ix_user_metric_user_id'), 'user_metric', ['user_id'], unique=False)
    op.create_table('workspace',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'name')
    )
    op.create_index(op.f('ix_workspace_brand_id'), 'workspace', ['brand_id'], unique=False)
    op.create_index(op.f('ix_workspace_company_id'), 'workspace', ['company_id'], unique=False)
    op.create_index(op.f('ix_workspace_created_by'), 'workspace', ['created_by'], unique=False)
    op.create_index(op.f('ix_workspace_name'), 'workspace', ['name'], unique=False)
    op.create_index(op.f('ix_workspace_updated_by'), 'workspace', ['updated_by'], unique=False)
    op.create_table('integration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('datasource_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'SYNCING', name='integrationstatus'), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_company_id'), 'integration', ['company_id'], unique=False)
    op.create_index(op.f('ix_integration_datasource_id'), 'integration', ['datasource_id'], unique=False)
    op.create_index(op.f('ix_integration_workspace_id'), 'integration', ['workspace_id'], unique=False)
    op.create_table('workspace_membership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='systemrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_index(op.f('ix_workspace_membership_user_id'), 'workspace_membership', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_membership_workspace_id'), 'workspace_membership', ['workspace_id'], unique=False)
    op.create_table('integration_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('sync_attempts', sa.Integer(), nullable=False),
    sa.Column('sync_successes', sa.Integer(), nullable=False),
    sa.Column('sync_failures', sa.Integer(), nullable=False),
    sa.Column('avg_sync_duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_records_synced', sa.Integer(), nullable=False),
    sa.Column('total_data_volume_bytes', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_metric_company_id'), 'integration_metric', ['company_id'], unique=False)
    op.create_index(op.f('ix_integration_metric_integration_id'), 'integration_metric', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_metric_metric_date'), 'integration_metric', ['metric_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_metric_metric_date'), table_name='integration_metric')
    op.drop_index(op.f('ix_integration_metric_integration_id'), table_name='integration_metric')
    op.drop_index(op.f('ix_integration_metric_company_id'), table_name='integration_metric')
    op.drop_table('integration_metric')
    op.drop_index(op.f('ix_workspace_membership_workspace_id'), table_name='workspace_membership')
    op.drop_index(op.f('ix_workspace_membership_user_id'), table_name='workspace_membership')
    op.drop_table('workspace_membership')
    op.drop_index(op.f('ix_integration_workspace_id'), table_name='integration')
    op.drop_index(op.f('ix_integration_datasource_id'), table_name='integration')
    op.drop_index(op.f('ix_integration_company_id'), table_name='integration')
    op.drop_table('integration')
    op.drop_index(op.f('ix_workspace_updated_by'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_name'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_created_by'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_company_id'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_brand_id'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_user_metric_user_id'), table_name='user_metric')
    op.drop_index(op.f('ix_user_metric_metric_date'), table_name='user_metric')
    op.drop_table('user_metric')
    op.drop_index(op.f('ix_onboarding_metric_user_id'), table_name='onboarding_metric')
    op.drop_table('onboarding_metric')
    op.drop_index(op.f('ix_company_membership_user_id'), table_name='company_membership')
    op.drop_index(op.f('ix_company_membership_company_id'), table_name='company_membership')
    op.drop_table('company_membership')
    op.drop_index(op.f('ix_company_entitlement_module_id'), table_name='company_entitlement')
    op.drop_index(op.f('ix_company_entitlement_company_id'), table_name='company_entitlement')
    op.drop_table('company_entitlement')
    op.drop_index(op.f('ix_brand_updated_by'), table_name='brand')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_index(op.f('ix_brand_created_by'), table_name='brand')
    op.drop_index(op.f('ix_brand_company_id'), table_name='brand')
    op.drop_table('brand')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_system_metric_timestamp'), table_name='system_metric')
    op.drop_table('system_metric')
    op.drop_table('permission')
    op.drop_index(op.f('ix_onboarding_state_user_id'), table_name='onboarding_state')
    op.drop_index(op.f('ix_onboarding_state_updated_by'), table_name='onboarding_state')
    op.drop_index(op.f('ix_onboarding_state_created_by'), table_name='onboarding_state')
    op.drop_table('onboarding_state')
    op.drop_table('module')
    op.drop_index(op.f('ix_data_source_request_user_id'), table_name='data_source_request')
    op.drop_index(op.f('ix_data_source_request_name'), table_name='data_source_request')
    op.drop_table('data_source_request')
    op.drop_index(op.f('ix_data_source_slug'), table_name='data_source')
    op.drop_index(op.f('ix_data_source_name'), table_name='data_source')
    op.drop_index(op.f('ix_data_source_category'), table_name='data_source')
    op.drop_table('data_source')
    op.drop_index(op.f('ix_company_updated_by'), table_name='company')
    op.drop_index(op.f('ix_company_created_by'), table_name='company')
    op.drop_index(op.f('ix_company_brand_name'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_business_metric_metric_date'), table_name='business_metric')
    op.drop_table('business_metric')
    op.drop_index(op.f('ix_audit_trail_workspace_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_company_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_brand_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_actor_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_action'), table_name='audit_trail')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
