"""Add customer_id UUID to shopify_address

Revision ID: 3a1118d89c5c
Revises: 8b7bd6336694
Create Date: 2026-01-13 10:25:06.106621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a1118d89c5c'
down_revision: Union[str, Sequence[str], None] = '8b7bd6336694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopify_daily_metric_company_id'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_created_by'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_integration_id'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_snapshot_date'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_updated_by'), table_name='shopify_daily_metric')
    op.drop_table('shopify_daily_metric')
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    op.add_column('shopify_address', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.add_column('shopify_address', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_shopify_address_customer_id'), 'shopify_address', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'shopify_address', 'shopify_customer', ['customer_id'], ['id'], ondelete='CASCADE')
    op.add_column('shopify_customer', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('shopify_location', sa.Column('shopify_created_at', sa.DateTime(), nullable=True))
    op.add_column('shopify_location', sa.Column('shopify_updated_at', sa.DateTime(), nullable=True))
    op.add_column('shopify_location', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_shopify_location_shopify_created_at'), 'shopify_location', ['shopify_created_at'], unique=False)
    op.create_index(op.f('ix_shopify_location_shopify_updated_at'), 'shopify_location', ['shopify_updated_at'], unique=False)
    op.alter_column('shopify_product', 'shopify_created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shopify_product', 'shopify_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_shopify_product_shopify_created_at'), 'shopify_product', ['shopify_created_at'], unique=False)
    op.create_index(op.f('ix_shopify_product_shopify_updated_at'), 'shopify_product', ['shopify_updated_at'], unique=False)
    op.add_column('shopify_product_image', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('shopify_product_image', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('shopify_product_image', sa.Column('shopify_created_at', sa.DateTime(), nullable=True))
    op.add_column('shopify_product_image', sa.Column('shopify_updated_at', sa.DateTime(), nullable=True))
    op.add_column('shopify_product_image', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_shopify_product_image_shopify_created_at'), 'shopify_product_image', ['shopify_created_at'], unique=False)
    op.create_index(op.f('ix_shopify_product_image_shopify_updated_at'), 'shopify_product_image', ['shopify_updated_at'], unique=False)
    op.add_column('shopify_product_variant', sa.Column('shopify_created_at', sa.DateTime(), nullable=True))
    op.add_column('shopify_product_variant', sa.Column('shopify_updated_at', sa.DateTime(), nullable=True))
    op.add_column('shopify_product_variant', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_shopify_product_variant_shopify_created_at'), 'shopify_product_variant', ['shopify_created_at'], unique=False)
    op.create_index(op.f('ix_shopify_product_variant_shopify_updated_at'), 'shopify_product_variant', ['shopify_updated_at'], unique=False)
    op.add_column('shopify_refund', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('shopify_transaction', sa.Column('shopify_processed_at', sa.DateTime(), nullable=False))
    op.add_column('shopify_transaction', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_shopify_transaction_processed_at'), table_name='shopify_transaction')
    op.create_index(op.f('ix_shopify_transaction_shopify_processed_at'), 'shopify_transaction', ['shopify_processed_at'], unique=False)
    op.drop_column('shopify_transaction', 'processed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopify_transaction', sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_shopify_transaction_shopify_processed_at'), table_name='shopify_transaction')
    op.create_index(op.f('ix_shopify_transaction_processed_at'), 'shopify_transaction', ['processed_at'], unique=False)
    op.drop_column('shopify_transaction', 'raw_payload')
    op.drop_column('shopify_transaction', 'shopify_processed_at')
    op.drop_column('shopify_refund', 'raw_payload')
    op.drop_index(op.f('ix_shopify_product_variant_shopify_updated_at'), table_name='shopify_product_variant')
    op.drop_index(op.f('ix_shopify_product_variant_shopify_created_at'), table_name='shopify_product_variant')
    op.drop_column('shopify_product_variant', 'raw_payload')
    op.drop_column('shopify_product_variant', 'shopify_updated_at')
    op.drop_column('shopify_product_variant', 'shopify_created_at')
    op.drop_index(op.f('ix_shopify_product_image_shopify_updated_at'), table_name='shopify_product_image')
    op.drop_index(op.f('ix_shopify_product_image_shopify_created_at'), table_name='shopify_product_image')
    op.drop_column('shopify_product_image', 'raw_payload')
    op.drop_column('shopify_product_image', 'shopify_updated_at')
    op.drop_column('shopify_product_image', 'shopify_created_at')
    op.drop_column('shopify_product_image', 'height')
    op.drop_column('shopify_product_image', 'width')
    op.drop_index(op.f('ix_shopify_product_shopify_updated_at'), table_name='shopify_product')
    op.drop_index(op.f('ix_shopify_product_shopify_created_at'), table_name='shopify_product')
    op.alter_column('shopify_product', 'shopify_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shopify_product', 'shopify_created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_shopify_location_shopify_updated_at'), table_name='shopify_location')
    op.drop_index(op.f('ix_shopify_location_shopify_created_at'), table_name='shopify_location')
    op.drop_column('shopify_location', 'raw_payload')
    op.drop_column('shopify_location', 'shopify_updated_at')
    op.drop_column('shopify_location', 'shopify_created_at')
    op.drop_column('shopify_customer', 'raw_payload')
    op.drop_constraint(None, 'shopify_address', type_='foreignkey')
    op.drop_index(op.f('ix_shopify_address_customer_id'), table_name='shopify_address')
    op.drop_column('shopify_address', 'raw_payload')
    op.drop_column('shopify_address', 'customer_id')
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.create_table('shopify_daily_metric',
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('order_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_count_new', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_order_value', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('gross_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_discounts', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_refunds', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_tax', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_shipping', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('shopify_daily_metric_company_id_fkey')),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], name=op.f('shopify_daily_metric_integration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shopify_daily_metric_pkey')),
    sa.UniqueConstraint('integration_id', 'snapshot_date', name=op.f('shopify_daily_metric_integration_id_snapshot_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shopify_daily_metric_updated_by'), 'shopify_daily_metric', ['updated_by'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_snapshot_date'), 'shopify_daily_metric', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_integration_id'), 'shopify_daily_metric', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_created_by'), 'shopify_daily_metric', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_company_id'), 'shopify_daily_metric', ['company_id'], unique=False)
    # ### end Alembic commands ###
