"""Add ShopifyReport tables

Revision ID: 468f08500bb1
Revises: 76c2cb88780b
Create Date: 2026-01-13 05:36:46.785038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '468f08500bb1'
down_revision: Union[str, Sequence[str], None] = '76c2cb88780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_report',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('shopify_report_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shopify_ql', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shopify_updated_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'shopify_report_id')
    )
    op.create_index(op.f('ix_shopify_report_company_id'), 'shopify_report', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_report_created_by'), 'shopify_report', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_report_integration_id'), 'shopify_report', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_report_name'), 'shopify_report', ['name'], unique=False)
    op.create_index(op.f('ix_shopify_report_shopify_report_id'), 'shopify_report', ['shopify_report_id'], unique=False)
    op.create_index(op.f('ix_shopify_report_shopify_updated_at'), 'shopify_report', ['shopify_updated_at'], unique=False)
    op.create_index(op.f('ix_shopify_report_updated_by'), 'shopify_report', ['updated_by'], unique=False)
    op.create_table('shopify_report_data',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('query_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['shopify_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopify_report_data_captured_at'), 'shopify_report_data', ['captured_at'], unique=False)
    op.create_index(op.f('ix_shopify_report_data_company_id'), 'shopify_report_data', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_report_data_created_by'), 'shopify_report_data', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_report_data_integration_id'), 'shopify_report_data', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_report_data_query_name'), 'shopify_report_data', ['query_name'], unique=False)
    op.create_index(op.f('ix_shopify_report_data_updated_by'), 'shopify_report_data', ['updated_by'], unique=False)
    op.alter_column('integration', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'error', 'syncing', 'disconnect_requested', name='integrationstatus'),
               type_=sa.String(),
               nullable=True)
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.alter_column('integration', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('active', 'inactive', 'error', 'syncing', 'disconnect_requested', name='integrationstatus'),
               nullable=False)
    op.drop_index(op.f('ix_shopify_report_data_updated_by'), table_name='shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_data_query_name'), table_name='shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_data_integration_id'), table_name='shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_data_created_by'), table_name='shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_data_company_id'), table_name='shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_data_captured_at'), table_name='shopify_report_data')
    op.drop_table('shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_updated_by'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_shopify_updated_at'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_shopify_report_id'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_name'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_integration_id'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_created_by'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_company_id'), table_name='shopify_report')
    op.drop_table('shopify_report')
    # ### end Alembic commands ###
