"""add_campaign_goal_detail_and_update_campaign

Revision ID: 4da14d2480af
Revises: 32948d82da7f
Create Date: 2026-01-28 22:43:40.859605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4da14d2480af'
down_revision: Union[str, Sequence[str], None] = '32948d82da7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('bolna_raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_campaigns_interview_session_id'), table_name='campaigns')
    op.drop_column('campaigns', 'interview_session_id')
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.add_column('campaigns', sa.Column('interview_session_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_campaigns_interview_session_id'), 'campaigns', ['interview_session_id'], unique=False)
    op.drop_column('campaigns', 'bolna_raw_data')
    # ### end Alembic commands ###
