"""Add Shopify Reports and Analytics models

Revision ID: 6efcb5226d3e
Revises: bf01ad25ede0
Create Date: 2026-01-13 08:13:18.448766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6efcb5226d3e'
down_revision: Union[str, Sequence[str], None] = 'bf01ad25ede0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_report',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('shopify_report_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shopify_ql', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shopify_updated_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'shopify_report_id')
    )
    op.create_index(op.f('ix_shopify_report_company_id'), 'shopify_report', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_report_created_by'), 'shopify_report', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_report_integration_id'), 'shopify_report', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_report_name'), 'shopify_report', ['name'], unique=False)
    op.create_index(op.f('ix_shopify_report_shopify_report_id'), 'shopify_report', ['shopify_report_id'], unique=False)
    op.create_index(op.f('ix_shopify_report_shopify_updated_at'), 'shopify_report', ['shopify_updated_at'], unique=False)
    op.create_index(op.f('ix_shopify_report_updated_by'), 'shopify_report', ['updated_by'], unique=False)
    op.create_table('shopify_report_data',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('query_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['shopify_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopify_report_data_captured_at'), 'shopify_report_data', ['captured_at'], unique=False)
    op.create_index(op.f('ix_shopify_report_data_company_id'), 'shopify_report_data', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_report_data_created_by'), 'shopify_report_data', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_report_data_integration_id'), 'shopify_report_data', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_report_data_query_name'), 'shopify_report_data', ['query_name'], unique=False)
    op.create_index(op.f('ix_shopify_report_data_updated_by'), 'shopify_report_data', ['updated_by'], unique=False)
    op.create_table('shopify_analytics_snapshot',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('report_data_id', sa.Uuid(), nullable=True),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('granularity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_data_id'], ['shopify_report_data.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['shopify_report.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'report_data_id', 'timestamp', 'granularity')
    )
    op.create_index(op.f('ix_shopify_analytics_snapshot_company_id'), 'shopify_analytics_snapshot', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_analytics_snapshot_created_by'), 'shopify_analytics_snapshot', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_analytics_snapshot_granularity'), 'shopify_analytics_snapshot', ['granularity'], unique=False)
    op.create_index(op.f('ix_shopify_analytics_snapshot_integration_id'), 'shopify_analytics_snapshot', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_analytics_snapshot_timestamp'), 'shopify_analytics_snapshot', ['timestamp'], unique=False)
    op.create_index(op.f('ix_shopify_analytics_snapshot_updated_by'), 'shopify_analytics_snapshot', ['updated_by'], unique=False)
    op.drop_index(op.f('ix_shopify_daily_metric_company_id'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_created_by'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_integration_id'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_snapshot_date'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_updated_by'), table_name='shopify_daily_metric')
    op.drop_table('shopify_daily_metric')
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.create_table('shopify_daily_metric',
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('order_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_count_new', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_order_value', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('gross_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_discounts', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_refunds', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_tax', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_shipping', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('shopify_daily_metric_company_id_fkey')),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], name=op.f('shopify_daily_metric_integration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shopify_daily_metric_pkey')),
    sa.UniqueConstraint('integration_id', 'snapshot_date', name=op.f('shopify_daily_metric_integration_id_snapshot_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shopify_daily_metric_updated_by'), 'shopify_daily_metric', ['updated_by'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_snapshot_date'), 'shopify_daily_metric', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_integration_id'), 'shopify_daily_metric', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_created_by'), 'shopify_daily_metric', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_company_id'), 'shopify_daily_metric', ['company_id'], unique=False)
    op.drop_index(op.f('ix_shopify_analytics_snapshot_updated_by'), table_name='shopify_analytics_snapshot')
    op.drop_index(op.f('ix_shopify_analytics_snapshot_timestamp'), table_name='shopify_analytics_snapshot')
    op.drop_index(op.f('ix_shopify_analytics_snapshot_integration_id'), table_name='shopify_analytics_snapshot')
    op.drop_index(op.f('ix_shopify_analytics_snapshot_granularity'), table_name='shopify_analytics_snapshot')
    op.drop_index(op.f('ix_shopify_analytics_snapshot_created_by'), table_name='shopify_analytics_snapshot')
    op.drop_index(op.f('ix_shopify_analytics_snapshot_company_id'), table_name='shopify_analytics_snapshot')
    op.drop_table('shopify_analytics_snapshot')
    op.drop_index(op.f('ix_shopify_report_data_updated_by'), table_name='shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_data_query_name'), table_name='shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_data_integration_id'), table_name='shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_data_created_by'), table_name='shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_data_company_id'), table_name='shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_data_captured_at'), table_name='shopify_report_data')
    op.drop_table('shopify_report_data')
    op.drop_index(op.f('ix_shopify_report_updated_by'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_shopify_updated_at'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_shopify_report_id'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_name'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_integration_id'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_created_by'), table_name='shopify_report')
    op.drop_index(op.f('ix_shopify_report_company_id'), table_name='shopify_report')
    op.drop_table('shopify_report')
    # ### end Alembic commands ###
