"""add_cohort_incentives_missing_cols

Revision ID: 7039e193cd60
Revises: 951faa51dd8a
Create Date: 2026-02-04 06:08:04.446831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7039e193cd60'
down_revision: Union[str, Sequence[str], None] = '951faa51dd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['campaign_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_events_campaign_id'), 'campaign_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_events_created_at'), 'campaign_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_events_event_type'), 'campaign_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_campaign_events_lead_id'), 'campaign_events', ['lead_id'], unique=False)
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    
    # Safely add columns only if they don't exist
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    existing_columns = [c['name'] for c in inspector.get_columns('campaigns')]

    if 'cohort_incentives' not in existing_columns:
        op.add_column('campaigns', sa.Column('cohort_incentives', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    if 'cohort_questions' not in existing_columns:
        op.add_column('campaigns', sa.Column('cohort_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_campaign_events_lead_id'), table_name='campaign_events')
    op.drop_index(op.f('ix_campaign_events_event_type'), table_name='campaign_events')
    op.drop_index(op.f('ix_campaign_events_created_at'), table_name='campaign_events')
    op.drop_index(op.f('ix_campaign_events_campaign_id'), table_name='campaign_events')
    op.drop_table('campaign_events')
    # ### end Alembic commands ###
