"""initial_schema

Revision ID: 7668d5c0397f
Revises: 
Create Date: 2025-12-29 02:42:41.622648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7668d5c0397f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audittrail',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audittrail_action'), 'audittrail', ['action'], unique=False)
    op.create_index(op.f('ix_audittrail_actor_id'), 'audittrail', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audittrail_brand_id'), 'audittrail', ['brand_id'], unique=False)
    op.create_index(op.f('ix_audittrail_company_id'), 'audittrail', ['company_id'], unique=False)
    op.create_index(op.f('ix_audittrail_workspace_id'), 'audittrail', ['workspace_id'], unique=False)
    op.create_table('business_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('active_users_daily', sa.Integer(), nullable=False),
    sa.Column('active_users_weekly', sa.Integer(), nullable=False),
    sa.Column('active_users_monthly', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('churned_users', sa.Integer(), nullable=False),
    sa.Column('total_companies', sa.Integer(), nullable=False),
    sa.Column('new_companies', sa.Integer(), nullable=False),
    sa.Column('active_companies', sa.Integer(), nullable=False),
    sa.Column('total_workspaces', sa.Integer(), nullable=False),
    sa.Column('new_workspaces', sa.Integer(), nullable=False),
    sa.Column('active_workspaces', sa.Integer(), nullable=False),
    sa.Column('total_integrations', sa.Integer(), nullable=False),
    sa.Column('new_integrations', sa.Integer(), nullable=False),
    sa.Column('active_integrations', sa.Integer(), nullable=False),
    sa.Column('onboarding_started', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Integer(), nullable=False),
    sa.Column('onboarding_completion_rate', sa.Float(), nullable=False),
    sa.Column('avg_session_duration_seconds', sa.Float(), nullable=True),
    sa.Column('avg_page_views_per_user', sa.Float(), nullable=True),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('arr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_metrics_metric_date'), 'business_metrics', ['metric_date'], unique=True)
    op.create_table('company',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_table('datasource_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasource_requests_name'), 'datasource_requests', ['name'], unique=False)
    op.create_index(op.f('ix_datasource_requests_user_id'), 'datasource_requests', ['user_id'], unique=False)
    op.create_table('datasources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('Storefront', 'Marketplace', 'QuickCommerce', 'Network', 'SocialCommerce', 'Marketing', 'Logistics', 'Payment', 'Accounting', 'Analytics', 'Communication', 'Retention', name='datasourcecategory'), nullable=False),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_coming_soon', sa.Boolean(), nullable=False),
    sa.Column('is_common', sa.Boolean(), nullable=False),
    sa.Column('is_implemented', sa.Boolean(), nullable=False),
    sa.Column('theme_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasources_category'), 'datasources', ['category'], unique=False)
    op.create_index(op.f('ix_datasources_name'), 'datasources', ['name'], unique=True)
    op.create_index(op.f('ix_datasources_slug'), 'datasources', ['slug'], unique=True)
    op.create_table('module',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboardingstate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_page', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('basics_data', sa.JSON(), nullable=True),
    sa.Column('channels_data', sa.JSON(), nullable=True),
    sa.Column('stack_data', sa.JSON(), nullable=True),
    sa.Column('finish_data', sa.JSON(), nullable=True),
    sa.Column('identity_data', sa.JSON(), nullable=True),
    sa.Column('truth_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_saved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboardingstate_user_id'), 'onboardingstate', ['user_id'], unique=True)
    op.create_table('permission',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('api_requests_total', sa.Integer(), nullable=False),
    sa.Column('api_requests_success', sa.Integer(), nullable=False),
    sa.Column('api_requests_error', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('db_connections_active', sa.Integer(), nullable=False),
    sa.Column('db_query_avg_time_ms', sa.Float(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('memory_usage_percent', sa.Float(), nullable=True),
    sa.Column('overall_health_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('brand',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name')
    )
    op.create_index(op.f('ix_brand_company_id'), 'brand', ['company_id'], unique=False)
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=False)
    op.create_table('companyentitlement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'module_id')
    )
    op.create_index(op.f('ix_companyentitlement_company_id'), 'companyentitlement', ['company_id'], unique=False)
    op.create_index(op.f('ix_companyentitlement_module_id'), 'companyentitlement', ['module_id'], unique=False)
    op.create_table('companymembership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='systemrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id')
    )
    op.create_index(op.f('ix_companymembership_company_id'), 'companymembership', ['company_id'], unique=False)
    op.create_index(op.f('ix_companymembership_user_id'), 'companymembership', ['user_id'], unique=False)
    op.create_table('onboarding_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(), nullable=True),
    sa.Column('basics_completed_at', sa.DateTime(), nullable=True),
    sa.Column('channels_completed_at', sa.DateTime(), nullable=True),
    sa.Column('stack_completed_at', sa.DateTime(), nullable=True),
    sa.Column('finish_completed_at', sa.DateTime(), nullable=True),
    sa.Column('basics_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('channels_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('stack_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('finish_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('drawer_opens', sa.Integer(), nullable=False),
    sa.Column('search_uses', sa.Integer(), nullable=False),
    sa.Column('datasources_selected', sa.Integer(), nullable=False),
    sa.Column('integration_requests', sa.Integer(), nullable=False),
    sa.Column('last_step_visited', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drop_off_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_metrics_user_id'), 'onboarding_metrics', ['user_id'], unique=True)
    op.create_table('user_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('total_session_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('interactions', sa.Integer(), nullable=False),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_metrics_metric_date'), 'user_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_user_metrics_user_id'), 'user_metrics', ['user_id'], unique=False)
    op.create_table('workspace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'name')
    )
    op.create_index(op.f('ix_workspace_brand_id'), 'workspace', ['brand_id'], unique=False)
    op.create_index(op.f('ix_workspace_company_id'), 'workspace', ['company_id'], unique=False)
    op.create_index(op.f('ix_workspace_name'), 'workspace', ['name'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('datasource_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'SYNCING', name='integrationstatus'), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_datasource_id'), 'integrations', ['datasource_id'], unique=False)
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    op.create_table('workspacemembership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='systemrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_index(op.f('ix_workspacemembership_user_id'), 'workspacemembership', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspacemembership_workspace_id'), 'workspacemembership', ['workspace_id'], unique=False)
    op.create_table('integration_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('sync_attempts', sa.Integer(), nullable=False),
    sa.Column('sync_successes', sa.Integer(), nullable=False),
    sa.Column('sync_failures', sa.Integer(), nullable=False),
    sa.Column('avg_sync_duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_records_synced', sa.Integer(), nullable=False),
    sa.Column('total_data_volume_bytes', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_metrics_integration_id'), 'integration_metrics', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_metrics_metric_date'), 'integration_metrics', ['metric_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_metrics_metric_date'), table_name='integration_metrics')
    op.drop_index(op.f('ix_integration_metrics_integration_id'), table_name='integration_metrics')
    op.drop_table('integration_metrics')
    op.drop_index(op.f('ix_workspacemembership_workspace_id'), table_name='workspacemembership')
    op.drop_index(op.f('ix_workspacemembership_user_id'), table_name='workspacemembership')
    op.drop_table('workspacemembership')
    op.drop_index(op.f('ix_integrations_workspace_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_datasource_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_workspace_name'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_company_id'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_brand_id'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_user_metrics_user_id'), table_name='user_metrics')
    op.drop_index(op.f('ix_user_metrics_metric_date'), table_name='user_metrics')
    op.drop_table('user_metrics')
    op.drop_index(op.f('ix_onboarding_metrics_user_id'), table_name='onboarding_metrics')
    op.drop_table('onboarding_metrics')
    op.drop_index(op.f('ix_companymembership_user_id'), table_name='companymembership')
    op.drop_index(op.f('ix_companymembership_company_id'), table_name='companymembership')
    op.drop_table('companymembership')
    op.drop_index(op.f('ix_companyentitlement_module_id'), table_name='companyentitlement')
    op.drop_index(op.f('ix_companyentitlement_company_id'), table_name='companyentitlement')
    op.drop_table('companyentitlement')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_index(op.f('ix_brand_company_id'), table_name='brand')
    op.drop_table('brand')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_table('permission')
    op.drop_index(op.f('ix_onboardingstate_user_id'), table_name='onboardingstate')
    op.drop_table('onboardingstate')
    op.drop_table('module')
    op.drop_index(op.f('ix_datasources_slug'), table_name='datasources')
    op.drop_index(op.f('ix_datasources_name'), table_name='datasources')
    op.drop_index(op.f('ix_datasources_category'), table_name='datasources')
    op.drop_table('datasources')
    op.drop_index(op.f('ix_datasource_requests_user_id'), table_name='datasource_requests')
    op.drop_index(op.f('ix_datasource_requests_name'), table_name='datasource_requests')
    op.drop_table('datasource_requests')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_business_metrics_metric_date'), table_name='business_metrics')
    op.drop_table('business_metrics')
    op.drop_index(op.f('ix_audittrail_workspace_id'), table_name='audittrail')
    op.drop_index(op.f('ix_audittrail_company_id'), table_name='audittrail')
    op.drop_index(op.f('ix_audittrail_brand_id'), table_name='audittrail')
    op.drop_index(op.f('ix_audittrail_actor_id'), table_name='audittrail')
    op.drop_index(op.f('ix_audittrail_action'), table_name='audittrail')
    op.drop_table('audittrail')
    # ### end Alembic commands ###
