"""add shipping fields to shopify order

Revision ID: 76c2cb88780b
Revises: c4761c695970
Create Date: 2026-01-12 21:11:20.853938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '76c2cb88780b'
down_revision: Union[str, Sequence[str], None] = 'c4761c695970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopify_order', sa.Column('total_shipping', sa.Numeric(precision=20, scale=2), nullable=False, server_default='0'))
    op.add_column('shopify_order', sa.Column('total_shipping_tax', sa.Numeric(precision=20, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopify_order', 'total_shipping_tax')
    op.drop_column('shopify_order', 'total_shipping')
    # ### end Alembic commands ###
