"""Add onboarding_completed and summary fields

Revision ID: 7af7cc370ae2
Revises: e1e6dcc27106
Create Date: 2026-01-01 13:41:30.699896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7af7cc370ae2'
down_revision: Union[str, Sequence[str], None] = 'e1e6dcc27106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('stack_summary', sa.JSON(), nullable=True))
    op.add_column('company', sa.Column('channels_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'channels_summary')
    op.drop_column('company', 'stack_summary')
    # ### end Alembic commands ###
