"""Add Shopify Financial Tables

Revision ID: 87806129eb29
Revises: 468f08500bb1
Create Date: 2026-01-13 05:39:09.137935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87806129eb29'
down_revision: Union[str, Sequence[str], None] = '468f08500bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopify_daily_metric_company_id'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_created_by'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_integration_id'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_snapshot_date'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_updated_by'), table_name='shopify_daily_metric')
    op.drop_table('shopify_daily_metric')
    op.alter_column('integration', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'error', 'syncing', 'disconnect_requested', name='integrationstatus'),
               type_=sa.String(),
               nullable=True)
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.alter_column('integration', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('active', 'inactive', 'error', 'syncing', 'disconnect_requested', name='integrationstatus'),
               nullable=False)
    op.create_table('shopify_daily_metric',
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('order_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_count_new', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_order_value', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('gross_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_discounts', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_refunds', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_tax', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_shipping', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('shopify_daily_metric_company_id_fkey')),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], name=op.f('shopify_daily_metric_integration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shopify_daily_metric_pkey')),
    sa.UniqueConstraint('integration_id', 'snapshot_date', name=op.f('shopify_daily_metric_integration_id_snapshot_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shopify_daily_metric_updated_by'), 'shopify_daily_metric', ['updated_by'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_snapshot_date'), 'shopify_daily_metric', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_integration_id'), 'shopify_daily_metric', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_created_by'), 'shopify_daily_metric', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_company_id'), 'shopify_daily_metric', ['company_id'], unique=False)
    # ### end Alembic commands ###
