"""add call_raw_data table

Revision ID: 890c99c7c677
Revises: 7039e193cd60
Create Date: 2026-02-04 06:39:18.519675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '890c99c7c677'
down_revision: Union[str, Sequence[str], None] = '7039e193cd60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_raw_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('bolna_call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_raw_data_bolna_call_id'), 'call_raw_data', ['bolna_call_id'], unique=False)
    op.create_index(op.f('ix_call_raw_data_campaign_id'), 'call_raw_data', ['campaign_id'], unique=False)
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_call_raw_data_campaign_id'), table_name='call_raw_data')
    op.drop_index(op.f('ix_call_raw_data_bolna_call_id'), table_name='call_raw_data')
    op.drop_table('call_raw_data')
    # ### end Alembic commands ###
