"""add_onupdate_to_campaign_updated_at

Revision ID: 89fb972c85aa
Revises: 960ff26fa58e
Create Date: 2026-02-03 16:45:57.423084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89fb972c85aa'
down_revision: Union[str, Sequence[str], None] = '960ff26fa58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_bolna_call_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_campaign_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_lead_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    op.alter_column('queue_items', 'outcome',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_queue_items_campaign_lead'), 'queue_items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_queue_items_campaign_lead'), 'queue_items', ['campaign_id', 'lead_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('queue_items', 'outcome',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.create_table('call_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lead_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bolna_call_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bolna_agent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('termination_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transcript_summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recording_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('webhook_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('call_logs_campaign_id_fkey')),
    sa.ForeignKeyConstraint(['lead_id'], ['campaign_leads.id'], name=op.f('call_logs_lead_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('call_logs_pkey'))
    )
    op.create_index(op.f('ix_call_logs_lead_id'), 'call_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_call_logs_campaign_id'), 'call_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_call_logs_bolna_call_id'), 'call_logs', ['bolna_call_id'], unique=True)
    # ### end Alembic commands ###
