"""shift_shopify_ids_to_composite_unique

Revision ID: 8c6243a46871
Revises: d54787a093d5
Create Date: 2026-01-12 20:17:02.386846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c6243a46871'
down_revision: Union[str, Sequence[str], None] = 'd54787a093d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopify_address_shopify_address_id'), table_name='shopify_address')
    op.create_index(op.f('ix_shopify_address_shopify_address_id'), 'shopify_address', ['shopify_address_id'], unique=False)
    op.create_unique_constraint(None, 'shopify_address', ['integration_id', 'shopify_address_id'])
    op.drop_index(op.f('ix_shopify_customer_shopify_customer_id'), table_name='shopify_customer')
    op.create_index(op.f('ix_shopify_customer_shopify_customer_id'), 'shopify_customer', ['shopify_customer_id'], unique=False)
    op.create_unique_constraint(None, 'shopify_customer', ['integration_id', 'shopify_customer_id'])
    op.drop_index(op.f('ix_shopify_inventory_item_shopify_inventory_item_id'), table_name='shopify_inventory_item')
    op.create_index(op.f('ix_shopify_inventory_item_shopify_inventory_item_id'), 'shopify_inventory_item', ['shopify_inventory_item_id'], unique=False)
    op.create_unique_constraint(None, 'shopify_inventory_item', ['integration_id', 'shopify_inventory_item_id'])
    op.drop_index(op.f('ix_shopify_location_shopify_location_id'), table_name='shopify_location')
    op.create_index(op.f('ix_shopify_location_shopify_location_id'), 'shopify_location', ['shopify_location_id'], unique=False)
    op.create_unique_constraint(None, 'shopify_location', ['integration_id', 'shopify_location_id'])
    op.drop_index(op.f('ix_shopify_order_shopify_order_id'), table_name='shopify_order')
    op.create_index(op.f('ix_shopify_order_shopify_order_id'), 'shopify_order', ['shopify_order_id'], unique=False)
    op.create_unique_constraint(None, 'shopify_order', ['integration_id', 'shopify_order_id'])
    op.drop_index(op.f('ix_shopify_product_shopify_product_id'), table_name='shopify_product')
    op.create_index(op.f('ix_shopify_product_shopify_product_id'), 'shopify_product', ['shopify_product_id'], unique=False)
    op.create_unique_constraint(None, 'shopify_product', ['integration_id', 'shopify_product_id'])
    op.drop_index(op.f('ix_shopify_product_image_shopify_image_id'), table_name='shopify_product_image')
    op.create_index(op.f('ix_shopify_product_image_shopify_image_id'), 'shopify_product_image', ['shopify_image_id'], unique=False)
    op.create_unique_constraint(None, 'shopify_product_image', ['integration_id', 'shopify_image_id'])
    op.drop_index(op.f('ix_shopify_product_variant_shopify_variant_id'), table_name='shopify_product_variant')
    op.create_index(op.f('ix_shopify_product_variant_shopify_variant_id'), 'shopify_product_variant', ['shopify_variant_id'], unique=False)
    op.create_unique_constraint(None, 'shopify_product_variant', ['integration_id', 'shopify_variant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopify_product_variant', type_='unique')
    op.drop_index(op.f('ix_shopify_product_variant_shopify_variant_id'), table_name='shopify_product_variant')
    op.create_index(op.f('ix_shopify_product_variant_shopify_variant_id'), 'shopify_product_variant', ['shopify_variant_id'], unique=True)
    op.drop_constraint(None, 'shopify_product_image', type_='unique')
    op.drop_index(op.f('ix_shopify_product_image_shopify_image_id'), table_name='shopify_product_image')
    op.create_index(op.f('ix_shopify_product_image_shopify_image_id'), 'shopify_product_image', ['shopify_image_id'], unique=True)
    op.drop_constraint(None, 'shopify_product', type_='unique')
    op.drop_index(op.f('ix_shopify_product_shopify_product_id'), table_name='shopify_product')
    op.create_index(op.f('ix_shopify_product_shopify_product_id'), 'shopify_product', ['shopify_product_id'], unique=True)
    op.drop_constraint(None, 'shopify_order', type_='unique')
    op.drop_index(op.f('ix_shopify_order_shopify_order_id'), table_name='shopify_order')
    op.create_index(op.f('ix_shopify_order_shopify_order_id'), 'shopify_order', ['shopify_order_id'], unique=True)
    op.drop_constraint(None, 'shopify_location', type_='unique')
    op.drop_index(op.f('ix_shopify_location_shopify_location_id'), table_name='shopify_location')
    op.create_index(op.f('ix_shopify_location_shopify_location_id'), 'shopify_location', ['shopify_location_id'], unique=True)
    op.drop_constraint(None, 'shopify_inventory_item', type_='unique')
    op.drop_index(op.f('ix_shopify_inventory_item_shopify_inventory_item_id'), table_name='shopify_inventory_item')
    op.create_index(op.f('ix_shopify_inventory_item_shopify_inventory_item_id'), 'shopify_inventory_item', ['shopify_inventory_item_id'], unique=True)
    op.drop_constraint(None, 'shopify_customer', type_='unique')
    op.drop_index(op.f('ix_shopify_customer_shopify_customer_id'), table_name='shopify_customer')
    op.create_index(op.f('ix_shopify_customer_shopify_customer_id'), 'shopify_customer', ['shopify_customer_id'], unique=True)
    op.drop_constraint(None, 'shopify_address', type_='unique')
    op.drop_index(op.f('ix_shopify_address_shopify_address_id'), table_name='shopify_address')
    op.create_index(op.f('ix_shopify_address_shopify_address_id'), 'shopify_address', ['shopify_address_id'], unique=True)
    # ### end Alembic commands ###
