"""add_diff_summary_to_raw_ingest

Revision ID: 8d3fcdb663a3
Revises: dce76f95cba0
Create Date: 2026-01-11 15:39:28.679641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d3fcdb663a3'
down_revision: Union[str, Sequence[str], None] = 'dce76f95cba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopify_raw_ingest', sa.Column('diff_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopify_raw_ingest', 'diff_summary')
    # ### end Alembic commands ###
