"""add_unique_campaign_lead_phone_constraint

Revision ID: 951faa51dd8a
Revises: 0d34b225120a
Create Date: 2026-02-03 22:35:05.834046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '951faa51dd8a'
down_revision: Union[str, Sequence[str], None] = '0d34b225120a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_campaign_lead_phone', 'campaign_leads', ['campaign_id', 'contact_number'])
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_campaign_lead_phone', 'campaign_leads', type_='unique')
    # ### end Alembic commands ###
