"""add_insight_feedback_tables

Revision ID: bc27bf257031
Revises: d13ac66c435f
Create Date: 2026-01-15 19:58:49.797844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc27bf257031'
down_revision: Union[str, Sequence[str], None] = 'd13ac66c435f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_insight_log_brand_date'), table_name='insight_generation_log')
    op.drop_table('insight_generation_log')
    op.drop_index(op.f('idx_impression_brand_insight'), table_name='insight_impression')
    op.drop_table('insight_impression')
    op.drop_index(op.f('idx_suppression_brand'), table_name='insight_suppression')
    op.drop_table('insight_suppression')
    
    # Create new tables
    op.create_table('insight_feedback',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('insight_id', sa.String(), nullable=False),
        sa.Column('brand_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('verification_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('verification_status', sa.String(), server_default='PENDING', nullable=False),
        sa.Column('user_comment', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('verified_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_feedback_insight_id'), 'insight_feedback', ['insight_id'], unique=False)
    op.create_index(op.f('ix_insight_feedback_brand_id'), 'insight_feedback', ['brand_id'], unique=False)

    op.create_table('feedback_learning',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('brand_id', sa.UUID(), nullable=False),
        sa.Column('generator_type', sa.String(), nullable=False),
        sa.Column('refusal_reason', sa.String(), nullable=False),
        sa.Column('learning_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_learning_brand_id'), 'feedback_learning', ['brand_id'], unique=False)

    op.drop_index(op.f('idx_integration_workspace_status'), table_name='integration', postgresql_where="((status)::text = 'active'::text)")
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    op.drop_index(op.f('idx_daily_metric_integration_date'), table_name='shopify_daily_metric')
    op.drop_index(op.f('idx_inventory_level_integration_available'), table_name='shopify_inventory_level', postgresql_where='(available > 0)')
    op.create_index(op.f('ix_shopify_order_shopify_cancelled_at'), 'shopify_order', ['shopify_cancelled_at'], unique=False)
    op.drop_index(op.f('idx_workspace_brand'), table_name='workspace')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_workspace_brand'), 'workspace', ['brand_id'], unique=False)
    
    op.drop_index(op.f('ix_feedback_learning_brand_id'), table_name='feedback_learning')
    op.drop_table('feedback_learning')
    op.drop_index(op.f('ix_insight_feedback_brand_id'), table_name='insight_feedback')
    op.drop_index(op.f('ix_insight_feedback_insight_id'), table_name='insight_feedback')
    op.drop_table('insight_feedback')
    op.drop_index(op.f('ix_shopify_order_shopify_cancelled_at'), table_name='shopify_order')
    op.create_index(op.f('idx_inventory_level_integration_available'), 'shopify_inventory_level', ['integration_id', 'available'], unique=False, postgresql_where='(available > 0)')
    op.create_index(op.f('idx_daily_metric_integration_date'), 'shopify_daily_metric', ['integration_id', sa.literal_column('snapshot_date DESC')], unique=False)
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_integration_workspace_status'), 'integration', ['workspace_id', 'status'], unique=False, postgresql_where="((status)::text = 'active'::text)")
    op.create_table('insight_suppression',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('insight_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('suppressed_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('insight_suppression_brand_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('insight_suppression_pkey')),
    sa.UniqueConstraint('brand_id', 'insight_id', name=op.f('insight_suppression_brand_id_insight_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_suppression_brand'), 'insight_suppression', ['brand_id', 'suppressed_until'], unique=False)
    op.create_table('insight_impression',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('insight_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('shown_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('clicked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('dismissed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('action_taken', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('insight_impression_brand_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('insight_impression_pkey'))
    )
    op.create_index(op.f('idx_impression_brand_insight'), 'insight_impression', ['brand_id', 'insight_id'], unique=False)
    op.create_table('insight_generation_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('briefing', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generation_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('validation_failures', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('insight_generation_log_brand_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('insight_generation_log_pkey'))
    )
    op.create_index(op.f('idx_insight_log_brand_date'), 'insight_generation_log', ['brand_id', sa.literal_column('generated_at DESC')], unique=False)
    # ### end Alembic commands ###
