"""add_shopify_expansion_models

Revision ID: bca7318b0790
Revises: 3a1118d89c5c
Create Date: 2026-01-13 12:33:51.319064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bca7318b0790'
down_revision: Union[str, Sequence[str], None] = '3a1118d89c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_checkout',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('shopify_checkout_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cart_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('abandoned_checkout_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtotal_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shopify_created_at', sa.DateTime(), nullable=False),
    sa.Column('shopify_updated_at', sa.DateTime(), nullable=False),
    sa.Column('shopify_completed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'shopify_checkout_id')
    )
    op.create_index(op.f('ix_shopify_checkout_cart_token'), 'shopify_checkout', ['cart_token'], unique=False)
    op.create_index(op.f('ix_shopify_checkout_company_id'), 'shopify_checkout', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_checkout_created_by'), 'shopify_checkout', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_checkout_email'), 'shopify_checkout', ['email'], unique=False)
    op.create_index(op.f('ix_shopify_checkout_integration_id'), 'shopify_checkout', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_checkout_shopify_checkout_id'), 'shopify_checkout', ['shopify_checkout_id'], unique=False)
    op.create_index(op.f('ix_shopify_checkout_shopify_completed_at'), 'shopify_checkout', ['shopify_completed_at'], unique=False)
    op.create_index(op.f('ix_shopify_checkout_shopify_created_at'), 'shopify_checkout', ['shopify_created_at'], unique=False)
    op.create_index(op.f('ix_shopify_checkout_shopify_updated_at'), 'shopify_checkout', ['shopify_updated_at'], unique=False)
    op.create_index(op.f('ix_shopify_checkout_token'), 'shopify_checkout', ['token'], unique=False)
    op.create_index(op.f('ix_shopify_checkout_updated_by'), 'shopify_checkout', ['updated_by'], unique=False)
    op.create_table('shopify_marketing_event',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('shopify_marketing_event_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('marketing_channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('manage_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preview_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_to_end_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'shopify_marketing_event_id')
    )
    op.create_index(op.f('ix_shopify_marketing_event_company_id'), 'shopify_marketing_event', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_marketing_event_created_by'), 'shopify_marketing_event', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_marketing_event_ended_at'), 'shopify_marketing_event', ['ended_at'], unique=False)
    op.create_index(op.f('ix_shopify_marketing_event_integration_id'), 'shopify_marketing_event', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_marketing_event_marketing_channel'), 'shopify_marketing_event', ['marketing_channel'], unique=False)
    op.create_index(op.f('ix_shopify_marketing_event_shopify_marketing_event_id'), 'shopify_marketing_event', ['shopify_marketing_event_id'], unique=False)
    op.create_index(op.f('ix_shopify_marketing_event_started_at'), 'shopify_marketing_event', ['started_at'], unique=False)
    op.create_index(op.f('ix_shopify_marketing_event_type'), 'shopify_marketing_event', ['type'], unique=False)
    op.create_index(op.f('ix_shopify_marketing_event_updated_by'), 'shopify_marketing_event', ['updated_by'], unique=False)
    op.create_table('shopify_price_rule',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('shopify_price_rule_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_selection', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allocation_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('once_per_customer', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('shopify_created_at', sa.DateTime(), nullable=False),
    sa.Column('shopify_updated_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'shopify_price_rule_id')
    )
    op.create_index(op.f('ix_shopify_price_rule_allocation_method'), 'shopify_price_rule', ['allocation_method'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_company_id'), 'shopify_price_rule', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_created_by'), 'shopify_price_rule', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_ends_at'), 'shopify_price_rule', ['ends_at'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_integration_id'), 'shopify_price_rule', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_shopify_created_at'), 'shopify_price_rule', ['shopify_created_at'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_shopify_price_rule_id'), 'shopify_price_rule', ['shopify_price_rule_id'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_shopify_updated_at'), 'shopify_price_rule', ['shopify_updated_at'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_starts_at'), 'shopify_price_rule', ['starts_at'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_target_selection'), 'shopify_price_rule', ['target_selection'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_target_type'), 'shopify_price_rule', ['target_type'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_title'), 'shopify_price_rule', ['title'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_updated_by'), 'shopify_price_rule', ['updated_by'], unique=False)
    op.create_index(op.f('ix_shopify_price_rule_value_type'), 'shopify_price_rule', ['value_type'], unique=False)
    op.create_table('shopify_discount_code',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('price_rule_id', sa.Uuid(), nullable=False),
    sa.Column('shopify_price_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('shopify_discount_code_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('shopify_created_at', sa.DateTime(), nullable=False),
    sa.Column('shopify_updated_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_rule_id'], ['shopify_price_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'shopify_discount_code_id')
    )
    op.create_index(op.f('ix_shopify_discount_code_code'), 'shopify_discount_code', ['code'], unique=False)
    op.create_index(op.f('ix_shopify_discount_code_company_id'), 'shopify_discount_code', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_discount_code_created_by'), 'shopify_discount_code', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_discount_code_integration_id'), 'shopify_discount_code', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_discount_code_price_rule_id'), 'shopify_discount_code', ['price_rule_id'], unique=False)
    op.create_index(op.f('ix_shopify_discount_code_shopify_created_at'), 'shopify_discount_code', ['shopify_created_at'], unique=False)
    op.create_index(op.f('ix_shopify_discount_code_shopify_discount_code_id'), 'shopify_discount_code', ['shopify_discount_code_id'], unique=False)
    op.create_index(op.f('ix_shopify_discount_code_shopify_price_rule_id'), 'shopify_discount_code', ['shopify_price_rule_id'], unique=False)
    op.create_index(op.f('ix_shopify_discount_code_shopify_updated_at'), 'shopify_discount_code', ['shopify_updated_at'], unique=False)
    op.create_index(op.f('ix_shopify_discount_code_updated_by'), 'shopify_discount_code', ['updated_by'], unique=False)
    op.create_table('shopify_fulfillment',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('shopify_order_id', sa.BigInteger(), nullable=True),
    sa.Column('shopify_fulfillment_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shipment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('tracking_company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tracking_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shopify_created_at', sa.DateTime(), nullable=False),
    sa.Column('shopify_updated_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['shopify_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'shopify_fulfillment_id')
    )
    op.create_index(op.f('ix_shopify_fulfillment_company_id'), 'shopify_fulfillment', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_created_by'), 'shopify_fulfillment', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_integration_id'), 'shopify_fulfillment', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_order_id'), 'shopify_fulfillment', ['order_id'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_shipment_status'), 'shopify_fulfillment', ['shipment_status'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_shopify_created_at'), 'shopify_fulfillment', ['shopify_created_at'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_shopify_fulfillment_id'), 'shopify_fulfillment', ['shopify_fulfillment_id'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_shopify_order_id'), 'shopify_fulfillment', ['shopify_order_id'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_shopify_updated_at'), 'shopify_fulfillment', ['shopify_updated_at'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_status'), 'shopify_fulfillment', ['status'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_tracking_number'), 'shopify_fulfillment', ['tracking_number'], unique=False)
    op.create_index(op.f('ix_shopify_fulfillment_updated_by'), 'shopify_fulfillment', ['updated_by'], unique=False)
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    op.alter_column('shopify_product', 'body_html',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopify_product', 'body_html',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_shopify_fulfillment_updated_by'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_tracking_number'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_status'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_shopify_updated_at'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_shopify_order_id'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_shopify_fulfillment_id'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_shopify_created_at'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_shipment_status'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_order_id'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_integration_id'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_created_by'), table_name='shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_fulfillment_company_id'), table_name='shopify_fulfillment')
    op.drop_table('shopify_fulfillment')
    op.drop_index(op.f('ix_shopify_discount_code_updated_by'), table_name='shopify_discount_code')
    op.drop_index(op.f('ix_shopify_discount_code_shopify_updated_at'), table_name='shopify_discount_code')
    op.drop_index(op.f('ix_shopify_discount_code_shopify_price_rule_id'), table_name='shopify_discount_code')
    op.drop_index(op.f('ix_shopify_discount_code_shopify_discount_code_id'), table_name='shopify_discount_code')
    op.drop_index(op.f('ix_shopify_discount_code_shopify_created_at'), table_name='shopify_discount_code')
    op.drop_index(op.f('ix_shopify_discount_code_price_rule_id'), table_name='shopify_discount_code')
    op.drop_index(op.f('ix_shopify_discount_code_integration_id'), table_name='shopify_discount_code')
    op.drop_index(op.f('ix_shopify_discount_code_created_by'), table_name='shopify_discount_code')
    op.drop_index(op.f('ix_shopify_discount_code_company_id'), table_name='shopify_discount_code')
    op.drop_index(op.f('ix_shopify_discount_code_code'), table_name='shopify_discount_code')
    op.drop_table('shopify_discount_code')
    op.drop_index(op.f('ix_shopify_price_rule_value_type'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_updated_by'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_title'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_target_type'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_target_selection'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_starts_at'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_shopify_updated_at'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_shopify_price_rule_id'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_shopify_created_at'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_integration_id'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_ends_at'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_created_by'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_company_id'), table_name='shopify_price_rule')
    op.drop_index(op.f('ix_shopify_price_rule_allocation_method'), table_name='shopify_price_rule')
    op.drop_table('shopify_price_rule')
    op.drop_index(op.f('ix_shopify_marketing_event_updated_by'), table_name='shopify_marketing_event')
    op.drop_index(op.f('ix_shopify_marketing_event_type'), table_name='shopify_marketing_event')
    op.drop_index(op.f('ix_shopify_marketing_event_started_at'), table_name='shopify_marketing_event')
    op.drop_index(op.f('ix_shopify_marketing_event_shopify_marketing_event_id'), table_name='shopify_marketing_event')
    op.drop_index(op.f('ix_shopify_marketing_event_marketing_channel'), table_name='shopify_marketing_event')
    op.drop_index(op.f('ix_shopify_marketing_event_integration_id'), table_name='shopify_marketing_event')
    op.drop_index(op.f('ix_shopify_marketing_event_ended_at'), table_name='shopify_marketing_event')
    op.drop_index(op.f('ix_shopify_marketing_event_created_by'), table_name='shopify_marketing_event')
    op.drop_index(op.f('ix_shopify_marketing_event_company_id'), table_name='shopify_marketing_event')
    op.drop_table('shopify_marketing_event')
    op.drop_index(op.f('ix_shopify_checkout_updated_by'), table_name='shopify_checkout')
    op.drop_index(op.f('ix_shopify_checkout_token'), table_name='shopify_checkout')
    op.drop_index(op.f('ix_shopify_checkout_shopify_updated_at'), table_name='shopify_checkout')
    op.drop_index(op.f('ix_shopify_checkout_shopify_created_at'), table_name='shopify_checkout')
    op.drop_index(op.f('ix_shopify_checkout_shopify_completed_at'), table_name='shopify_checkout')
    op.drop_index(op.f('ix_shopify_checkout_shopify_checkout_id'), table_name='shopify_checkout')
    op.drop_index(op.f('ix_shopify_checkout_integration_id'), table_name='shopify_checkout')
    op.drop_index(op.f('ix_shopify_checkout_email'), table_name='shopify_checkout')
    op.drop_index(op.f('ix_shopify_checkout_created_by'), table_name='shopify_checkout')
    op.drop_index(op.f('ix_shopify_checkout_company_id'), table_name='shopify_checkout')
    op.drop_index(op.f('ix_shopify_checkout_cart_token'), table_name='shopify_checkout')
    op.drop_table('shopify_checkout')
    # ### end Alembic commands ###
