"""add_brand_metrics_table

Revision ID: d13ac66c435f
Revises: 41b134094295
Create Date: 2026-01-14 15:42:43.155730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd13ac66c435f'
down_revision: Union[str, Sequence[str], None] = '41b134094295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand_metric', 'total_revenue',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('brand_metric', 'total_inventory_value',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('ix_brand_metric_created_by'), table_name='brand_metric')
    op.drop_index(op.f('ix_brand_metric_updated_by'), table_name='brand_metric')
    op.drop_column('brand_metric', 'created_by')
    op.drop_column('brand_metric', 'updated_by')
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.add_column('brand_metric', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('brand_metric', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_brand_metric_updated_by'), 'brand_metric', ['updated_by'], unique=False)
    op.create_index(op.f('ix_brand_metric_created_by'), 'brand_metric', ['created_by'], unique=False)
    op.alter_column('brand_metric', 'total_inventory_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('brand_metric', 'total_revenue',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
