"""create_shopify_product_and_inventory_tables

Revision ID: dce76f95cba0
Revises: 50f81ba5c342
Create Date: 2026-01-11 14:20:52.311142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dce76f95cba0'
down_revision: Union[str, Sequence[str], None] = '50f81ba5c342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_log_event'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_integration_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_timestamp'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_topic'), table_name='activity_log')
    op.drop_table('activity_log')
    op.alter_column('integration', 'metadata_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('integration', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('integration', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('integration', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('shopify_customer', 'shopify_customer_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('shopify_customer', 'total_spent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('shopify_customer', 'accepts_marketing',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('shopify_line_item', 'shopify_line_item_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('shopify_order', 'shopify_order_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('shopify_order', 'refunded_subtotal',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('shopify_order', 'refunded_tax',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('shopify_product', sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shopify_product', sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shopify_product', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.alter_column('shopify_product', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shopify_product', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shopify_product', 'shopify_product_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_shopify_product_created_by'), 'shopify_product', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_product_handle'), 'shopify_product', ['handle'], unique=False)
    op.create_index(op.f('ix_shopify_product_product_type'), 'shopify_product', ['product_type'], unique=False)
    op.create_index(op.f('ix_shopify_product_published_at'), 'shopify_product', ['published_at'], unique=False)
    op.create_index(op.f('ix_shopify_product_status'), 'shopify_product', ['status'], unique=False)
    op.create_index(op.f('ix_shopify_product_title'), 'shopify_product', ['title'], unique=False)
    op.create_index(op.f('ix_shopify_product_updated_by'), 'shopify_product', ['updated_by'], unique=False)
    op.create_index(op.f('ix_shopify_product_vendor'), 'shopify_product', ['vendor'], unique=False)
    op.drop_column('shopify_product', 'created_at')
    op.drop_column('shopify_product', 'updated_at')
    op.alter_column('shopify_raw_ingest', 'shopify_object_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopify_raw_ingest', 'shopify_object_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.add_column('shopify_product', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('shopify_product', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_shopify_product_vendor'), table_name='shopify_product')
    op.drop_index(op.f('ix_shopify_product_updated_by'), table_name='shopify_product')
    op.drop_index(op.f('ix_shopify_product_title'), table_name='shopify_product')
    op.drop_index(op.f('ix_shopify_product_status'), table_name='shopify_product')
    op.drop_index(op.f('ix_shopify_product_published_at'), table_name='shopify_product')
    op.drop_index(op.f('ix_shopify_product_product_type'), table_name='shopify_product')
    op.drop_index(op.f('ix_shopify_product_handle'), table_name='shopify_product')
    op.drop_index(op.f('ix_shopify_product_created_by'), table_name='shopify_product')
    op.alter_column('shopify_product', 'shopify_product_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('shopify_product', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shopify_product', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('shopify_product', 'published_at')
    op.drop_column('shopify_product', 'tags')
    op.drop_column('shopify_product', 'handle')
    op.alter_column('shopify_order', 'refunded_tax',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('shopify_order', 'refunded_subtotal',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('shopify_order', 'shopify_order_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('shopify_line_item', 'shopify_line_item_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('shopify_customer', 'accepts_marketing',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('shopify_customer', 'total_spent',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('shopify_customer', 'shopify_customer_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('integration', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('integration', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('integration', 'last_sync_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('integration', 'metadata_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('activity_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], name=op.f('activity_log_integration_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_log_pkey'))
    )
    op.create_index(op.f('ix_activity_log_topic'), 'activity_log', ['topic'], unique=False)
    op.create_index(op.f('ix_activity_log_timestamp'), 'activity_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_log_integration_id'), 'activity_log', ['integration_id'], unique=False)
    op.create_index(op.f('ix_activity_log_event'), 'activity_log', ['event'], unique=False)
    # ### end Alembic commands ###
