"""create_shopify_raw_ingest_table

Revision ID: ddc2e7dd757e
Revises: c86ba245112d
Create Date: 2026-01-11 04:55:56.234925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ddc2e7dd757e'
down_revision: Union[str, Sequence[str], None] = 'c86ba245112d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_raw_ingest',
    sa.Column('headers', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shopify_object_id', sa.Integer(), nullable=False),
    sa.Column('shopify_updated_at', sa.DateTime(), nullable=True),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dedupe_hash_canonical', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hmac_valid', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopify_raw_ingest_company_id'), 'shopify_raw_ingest', ['company_id'], unique=False)
    op.create_index(op.f('ix_shopify_raw_ingest_created_by'), 'shopify_raw_ingest', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_raw_ingest_dedupe_hash_canonical'), 'shopify_raw_ingest', ['dedupe_hash_canonical'], unique=False)
    op.create_index(op.f('ix_shopify_raw_ingest_dedupe_key'), 'shopify_raw_ingest', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_shopify_raw_ingest_integration_id'), 'shopify_raw_ingest', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_raw_ingest_object_type'), 'shopify_raw_ingest', ['object_type'], unique=False)
    op.create_index(op.f('ix_shopify_raw_ingest_processing_status'), 'shopify_raw_ingest', ['processing_status'], unique=False)
    op.create_index(op.f('ix_shopify_raw_ingest_shopify_object_id'), 'shopify_raw_ingest', ['shopify_object_id'], unique=False)
    op.create_index(op.f('ix_shopify_raw_ingest_shopify_updated_at'), 'shopify_raw_ingest', ['shopify_updated_at'], unique=False)
    op.create_index(op.f('ix_shopify_raw_ingest_updated_by'), 'shopify_raw_ingest', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopify_raw_ingest_updated_by'), table_name='shopify_raw_ingest')
    op.drop_index(op.f('ix_shopify_raw_ingest_shopify_updated_at'), table_name='shopify_raw_ingest')
    op.drop_index(op.f('ix_shopify_raw_ingest_shopify_object_id'), table_name='shopify_raw_ingest')
    op.drop_index(op.f('ix_shopify_raw_ingest_processing_status'), table_name='shopify_raw_ingest')
    op.drop_index(op.f('ix_shopify_raw_ingest_object_type'), table_name='shopify_raw_ingest')
    op.drop_index(op.f('ix_shopify_raw_ingest_integration_id'), table_name='shopify_raw_ingest')
    op.drop_index(op.f('ix_shopify_raw_ingest_dedupe_key'), table_name='shopify_raw_ingest')
    op.drop_index(op.f('ix_shopify_raw_ingest_dedupe_hash_canonical'), table_name='shopify_raw_ingest')
    op.drop_index(op.f('ix_shopify_raw_ingest_created_by'), table_name='shopify_raw_ingest')
    op.drop_index(op.f('ix_shopify_raw_ingest_company_id'), table_name='shopify_raw_ingest')
    op.drop_table('shopify_raw_ingest')
    # ### end Alembic commands ###
