"""Add industry and country columns

Revision ID: e1e6dcc27106
Revises: 7668d5c0397f
Create Date: 2026-01-01 13:37:09.017744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1e6dcc27106'
down_revision: Union[str, Sequence[str], None] = '7668d5c0397f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'country')
    op.drop_column('company', 'industry')
    # ### end Alembic commands ###
