"""Seal proof reports and analytics models with cascades and metadata

Revision ID: e7d7aabe4f31
Revises: 6efcb5226d3e
Create Date: 2026-01-13 08:15:38.937607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7d7aabe4f31'
down_revision: Union[str, Sequence[str], None] = '6efcb5226d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopify_daily_metric_company_id'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_created_by'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_integration_id'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_snapshot_date'), table_name='shopify_daily_metric')
    op.drop_index(op.f('ix_shopify_daily_metric_updated_by'), table_name='shopify_daily_metric')
    op.drop_table('shopify_daily_metric')
    op.add_column('shopify_analytics_snapshot', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_shopify_analytics_snapshot_report_data_id'), 'shopify_analytics_snapshot', ['report_data_id'], unique=False)
    op.create_index(op.f('ix_shopify_analytics_snapshot_report_id'), 'shopify_analytics_snapshot', ['report_id'], unique=False)
    op.drop_constraint(op.f('shopify_analytics_snapshot_report_id_fkey'), 'shopify_analytics_snapshot', type_='foreignkey')
    op.drop_constraint(op.f('shopify_analytics_snapshot_report_data_id_fkey'), 'shopify_analytics_snapshot', type_='foreignkey')
    op.create_foreign_key(None, 'shopify_analytics_snapshot', 'shopify_report_data', ['report_data_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shopify_analytics_snapshot', 'shopify_report', ['report_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_shopify_report_data_report_id'), 'shopify_report_data', ['report_id'], unique=False)
    op.drop_constraint(op.f('shopify_report_data_report_id_fkey'), 'shopify_report_data', type_='foreignkey')
    op.create_foreign_key(None, 'shopify_report_data', 'shopify_report', ['report_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopify_report_data', type_='foreignkey')
    op.create_foreign_key(op.f('shopify_report_data_report_id_fkey'), 'shopify_report_data', 'shopify_report', ['report_id'], ['id'])
    op.drop_index(op.f('ix_shopify_report_data_report_id'), table_name='shopify_report_data')
    op.drop_constraint(None, 'shopify_analytics_snapshot', type_='foreignkey')
    op.drop_constraint(None, 'shopify_analytics_snapshot', type_='foreignkey')
    op.create_foreign_key(op.f('shopify_analytics_snapshot_report_data_id_fkey'), 'shopify_analytics_snapshot', 'shopify_report_data', ['report_data_id'], ['id'])
    op.create_foreign_key(op.f('shopify_analytics_snapshot_report_id_fkey'), 'shopify_analytics_snapshot', 'shopify_report', ['report_id'], ['id'])
    op.drop_index(op.f('ix_shopify_analytics_snapshot_report_id'), table_name='shopify_analytics_snapshot')
    op.drop_index(op.f('ix_shopify_analytics_snapshot_report_data_id'), table_name='shopify_analytics_snapshot')
    op.drop_column('shopify_analytics_snapshot', 'meta_data')
    op.create_table('shopify_daily_metric',
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('order_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_count_new', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_order_value', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('gross_sales', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_discounts', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_refunds', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_tax', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_shipping', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('shopify_daily_metric_company_id_fkey')),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], name=op.f('shopify_daily_metric_integration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shopify_daily_metric_pkey')),
    sa.UniqueConstraint('integration_id', 'snapshot_date', name=op.f('shopify_daily_metric_integration_id_snapshot_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shopify_daily_metric_updated_by'), 'shopify_daily_metric', ['updated_by'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_snapshot_date'), 'shopify_daily_metric', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_integration_id'), 'shopify_daily_metric', ['integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_created_by'), 'shopify_daily_metric', ['created_by'], unique=False)
    op.create_index(op.f('ix_shopify_daily_metric_company_id'), 'shopify_daily_metric', ['company_id'], unique=False)
    # ### end Alembic commands ###
