"""catch_up_sync

Revision ID: eb1bde87c0dd
Revises: 339be546ad27
Create Date: 2026-02-02 05:03:20.545768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb1bde87c0dd'
down_revision: Union[str, Sequence[str], None] = '339be546ad27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_session_company_id'), table_name='interview_session')
    op.drop_index(op.f('ix_interview_session_user_id'), table_name='interview_session')
    op.drop_table('interview_session')
    op.drop_constraint(op.f('integration_metric_integration_id_fkey'), 'integration_metric', type_='foreignkey')
    op.create_foreign_key(None, 'integration_metric', 'integration', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_metric', type_='foreignkey')
    op.create_foreign_key(op.f('integration_metric_integration_id_fkey'), 'integration_metric', 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
    op.create_table('interview_session',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_session_pkey'))
    )
    op.create_index(op.f('ix_interview_session_user_id'), 'interview_session', ['user_id'], unique=False)
    op.create_index(op.f('ix_interview_session_company_id'), 'interview_session', ['company_id'], unique=False)
    # ### end Alembic commands ###
